### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by MTRNord** [Nordgedanken/intellij-autohotkey#1]
- [ ] Add all language features to highlighting 
- [x] Add Usage logic
- [x] Cleanup grammar

All kinda blocked by me not yet knowing how everything works. I am still learning all this. And the Docs are not really that helpful beyond this point.

**Comment by takanuva15** [comment]
Closing this since it is a large multi-story epic. Will break this down into smaller tasks and schedule them over time
