### ISSUE TITLE
[REQUEST] Rename plugin to just "AutoHotkey"

### ISSUE THREAD

**Issue by takanuva15** [Nordgedanken/intellij-autohotkey#26]
I was looking at some of the other plugins on the intellij marketplace and I noticed that the plugin name is the same as the language name. Eg:
<img src="https://user-images.githubusercontent.com/6986426/87238083-02722080-c3cc-11ea-98c9-89510cf7f28a.png" height="300" />

Thus I recommend we should change the name of the plugin in the plugin.xml file from "AutoHotkey Language" to just "AutoHotkey". (I am not sure whether this requires any change on the JetBrains marketplace).

Note: I am just talking about the name of the plugin in plugin.xml and the jetbrains marketplace. The name of the GitHub repository should remain the same as it currently is.

**Comment by MTRNord** [comment]
I am actually not sure if that is possible in the marketplace :/

**Comment by takanuva15** [comment]
Interesting; could you try emailing jetbrains support to have them change the plugin name directly?
`marketplace AxT jetbrains.com`

**Comment by takanuva15** [comment]
Completed w release 0.5.0
