### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by MTRNord** [Nordgedanken/intellij-autohotkey#38]
I don't have the time or motivation to continue and I am looking for a new maintainer.

Considering @takanuva15 did a lot here if you want to you can get access to the project and I can transfer it. But I am personally not finding time or motivation to continue here.

**Comment by takanuva15** [comment]
@MTRNord Shoot...I respect that. Life throws different things at all of us lol. 

I'm okay with it if you choose to transfer the repository ownership to me.

**Comment by MTRNord** [comment]
@takanuva15 you now also have full admin access to the github repo.

**Comment by takanuva15** [comment]
Closing for now since we should be good. (I will re-open this if other priorities take over)
