### ISSUE TITLE
[REQUEST] Rename repo to "intellij-autohotkey"

### ISSUE THREAD

**Issue by takanuva15** [Nordgedanken/intellij-autohotkey#42]
Since most people who want to find a language plugin for their IDE will type the name of their IDE into google instead of the company name (eg "intellij rust", "clion cmake"), I think we can boost the visibility of this project a little more by renaming the project to "intellij-autohotkey". 

This name-change will also make the project more recognizable in Google results to newcomers who are familiar with intellij IDEs.

(I am thinking about making the change sometime next week. Please let me know if there are disagreements)

**Comment by MTRNord** [comment]
Done
