### ISSUE TITLE
[TODO] Change plugin package name to `com.autohotkey`

### ISSUE THREAD

**Issue by takanuva15** [Nordgedanken/intellij-autohotkey#72]
@MTRNord Hey hope life is treating you well. Not sure if you still monitor this repo, but I talked with the JetBrains developer team and they said we should be able to change the package name of our plugin with no impact on the plugin marketplace. Since that's the case, I figured we can make this plugin more "official" by changing the package name to `com.autohotkey` directly. (This will also help align the plugin with ktlint's Kotlin [code formatting standards](https://pinterest.github.io/ktlint/rules/experimental/#package-naming)).

Just wanted to check with you ahead of time to see if you had any issues doing that 👍

**Comment by MTRNord** [comment]
Hi I am passively following this repo :)

Feel free to do that. (if you want I guess I could also transfer the repo to you. In the end i am not doing anything on this anymore and you do the bulk of the work)

**Comment by takanuva15** [comment]
:D glad to see you're still around

> (if you want I guess I could also transfer the repo to you. In the end i am not doing anything on this anymore and you do the bulk of the work)

Sure no problem, I'm fine with doing that.

**Comment by MTRNord** [comment]
Well I would transfer the repo. Github however has other opinions :/

> You can only transfer a repository from an organization to yourself at this time

is the error I am getting :thinking:

**Comment by takanuva15** [comment]
Oop seems I never replied. No worries, GitHub has some funkiness to it. I spoke with the IntelliJ team and they said the plugin id must be the same, so I ended up just changing the package name to `com.autohotkey`.
