### ISSUE TITLE
IDEA installation plug-in error

### ISSUE THREAD

**Issue by Just-dot** [Nordgedanken/intellij-autohotkey#73]
IDEA version: IntelliJ IDEA 2023.1.1 (Ultimate Edition)
Build #IU-231.8770.65
AHK Plugin: IntelliJ-AutoHotkey-Plugin-v0.10.2
Source: https://plugins.jetbrains.com/plugin/13945-autohotkey/versions
An error was reported when installing the plugin in IDEA: The plugin 'AutoHotkey' (version '0.10.2') is not compatible with the current version of the IDE because it requires build number 223.* or older, but the current build number is IU-231.8770.65

**Comment by takanuva15** [comment]
Hi, thanks for reporting this issue. We are aware of this and are currently working to upgrade the plugin to support IntelliJ versions 2023 and later. The IntelliJ platform made some breaking code changes in their instrumentation which we are working to resolve. Once these issues are fixed, we will publish a new version and you should no longer see this error while installing.

**Comment by Just-dot** [comment]
Thank you very much! Can I know the approximate date of the new version release?

**Comment by Just-dot** [comment]
Thank you

**Comment by takanuva15** [comment]
Hi, can you try out this attached file and see if it works for you in IntelliJ 2023? 
(I'm still sorting out some issues but this should get you running in the meantime)

[IntelliJ AutoHotkey Plugin-0.10.3-alpha.zip](https://github.com/Nordgedanken/intellij-autohotkey/files/11498161/IntelliJ.AutoHotkey.Plugin-0.10.3-alpha.zip)

**Comment by Just-dot** [comment]
Thanks! I tried installing the plugin. And the installation is successful, but there is no prompt in the AHK file. I'm not quite sure if it's a plugin issue or my operation

**Comment by takanuva15** [comment]
Hmm...I'm not sure what you mean by "prompt in the AHK file". Right now this plugin does not have autocomplete working yet - the features that are available are listed in [the README](https://github.com/Nordgedanken/intellij-autohotkey#usage) under the "Usage" section.

**Comment by Just-dot** [comment]
grateful! I just looked up the "Usage" related. is available! The hints I mentioned refer to functions such as highlighting and code completion. Maybe not yet, I misunderstood.

**Comment by takanuva15** [comment]
v0.10.3 has been released which should be installable from the Plugin Marketplace. Closing this issue
