### ISSUE TITLE
[TODO] Documentation feature

### ISSUE THREAD

**Issue by MTRNord** [Nordgedanken/intellij-autohotkey#9]
**Tutorial:** https://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/documentation.html
**Difficulty:** Not sure but seems easier
**How Important:** Nice to have but not important

**Comment by amynbe** [comment]
Can you assign me this issue please

**Comment by takanuva15** [comment]
Completed with PR #54 (If any new issues arise or additional documentation support should be added, please raise a new issue)
